
import java.awt.Desktop;
import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.commons.lang.StringEscapeUtils;
import org.openqa.selenium.firefox.FirefoxDriver;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author VVK
 */
public class Xelenium extends javax.swing.JFrame {

    private final Vector<String> myVector = new Vector<String>();
    public HashMap<String,String> map = new HashMap<String,String>();
    public String logincreds = "";
    public String log_text;
    public Date Date_logger;    
    public ByteArrayOutputStream myOut = new ByteArrayOutputStream();
    public String stdOput;
    /**
     * Creates new form Xelenium
     */
    public Xelenium() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Log_Tab = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        URL_Txt_Field = new javax.swing.JTextField();
        Capture_Pages = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Captured_Pages_List = new javax.swing.JList();
        Remove_Btn = new javax.swing.JButton();
        Perform_XSSScan = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Uname_txt_field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Pwd_txt_field = new javax.swing.JTextField();
        Pwd_Protected_chkbox = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Avl_Atk_Vctr = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Sel_Atk_Vctr = new javax.swing.JList();
        Add = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Atk_Vctr_TxtField = new javax.swing.JTextField();
        Include = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Log_Textarea = new javax.swing.JTextArea();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        Log_Tab.setAutoscrolls(true);
        Log_Tab.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Enter URL:");

        Capture_Pages.setText("Capture Pages");
        Capture_Pages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Capture_PagesActionPerformed(evt);
            }
        });

        jLabel2.setText("Captured Pages: ");

        jScrollPane1.setViewportView(Captured_Pages_List);

        Remove_Btn.setText("Remove");
        Remove_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove_BtnActionPerformed(evt);
            }
        });

        Perform_XSSScan.setText("Perform XSS Scan");
        Perform_XSSScan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Perform_XSSScanActionPerformed(evt);
            }
        });

        jButton1.setText("Stop Scan");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login Creds:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jLabel6.setText("Username :");

        Uname_txt_field.setEnabled(false);

        jLabel7.setText("Password :");

        Pwd_txt_field.setEnabled(false);
        Pwd_txt_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pwd_txt_fieldActionPerformed(evt);
            }
        });

        Pwd_Protected_chkbox.setText("Password Protected ?");
        Pwd_Protected_chkbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pwd_Protected_chkboxMouseClicked(evt);
            }
        });
        Pwd_Protected_chkbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Pwd_Protected_chkboxItemStateChanged(evt);
            }
        });
        Pwd_Protected_chkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pwd_Protected_chkboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Pwd_Protected_chkbox)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Pwd_txt_field, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Uname_txt_field, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Pwd_Protected_chkbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Uname_txt_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Pwd_txt_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(44, 44, 44)
                                .addComponent(URL_Txt_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(142, 142, 142)
                                        .addComponent(Capture_Pages)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(Remove_Btn))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(Perform_XSSScan)))
                .addContainerGap(20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(URL_Txt_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Capture_Pages)
                                .addGap(38, 38, 38)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addComponent(Remove_Btn)
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Perform_XSSScan))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Log_Tab.addTab("Capture & Scan", jPanel2);

        jLabel3.setText("Available Attack Vectors:");

        Avl_Atk_Vctr.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "attack1", "attack2", "attack3", "attack4" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(Avl_Atk_Vctr);

        jLabel4.setText("Selected Attack Vectors:");

        Sel_Atk_Vctr.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "attack5", "attack6", "<SCRIPT <B>alert(123);</SCRIPT>", "<<SCRIPT>alert(123);//<</SCRIPT>", "<SCRIPT>alert(123);</SCRIPT>" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(Sel_Atk_Vctr);

        Add.setText("Add >>");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Remove.setText("Remove<<");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });

        jLabel5.setText("Attack Vector:");

        Include.setText("Include");
        Include.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncludeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Atk_Vctr_TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(Include, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Remove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(115, 115, 115))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(Add)
                        .addGap(86, 86, 86)
                        .addComponent(Remove)
                        .addGap(89, 89, 89)
                        .addComponent(Delete))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Atk_Vctr_TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Include))
                .addGap(59, 59, 59))
        );

        Log_Tab.addTab("Attack Vectors", jPanel3);

        Log_Textarea.setBackground(new java.awt.Color(240, 240, 240));
        Log_Textarea.setColumns(20);
        Log_Textarea.setEditable(false);
        Log_Textarea.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        Log_Textarea.setRows(5);
        Log_Textarea.setDisabledTextColor(new java.awt.Color(255, 0, 102));
        Log_Textarea.setSelectedTextColor(new java.awt.Color(255, 102, 102));
        jScrollPane4.setViewportView(Log_Textarea);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );

        Log_Tab.addTab("Log", jPanel6);

        jTabbedPane1.addTab("Xelenium", Log_Tab);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Capture_PagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Capture_PagesActionPerformed
        // TODO add your handling code here:
        String URL_prov = URL_Txt_Field.getText();
        if (!(URL_prov.equalsIgnoreCase(""))){
        
            if((URL_prov.startsWith("http://")) || (URL_prov.startsWith("https://"))){  
                FirefoxDriver d1 = new FirefoxDriver();
                d1.get(URL_Txt_Field.getText());
                String URLs[] = new String[1];
                String Dum_URLs[] = new String[1];
                String xUrl;
                URLs[0] = d1.getCurrentUrl();
                Dum_URLs[0] = d1.getCurrentUrl();
                try {
                    while (true) {
                        xUrl = d1.getCurrentUrl();
                        if (!((URLs[URLs.length - 1]).equalsIgnoreCase(xUrl))) {
                        Dum_URLs = new String[Dum_URLs.length + 1];
                        System.arraycopy(URLs, 0, Dum_URLs, 0, URLs.length);
                        Dum_URLs[Dum_URLs.length - 1] = d1.getCurrentUrl();
                        URLs = new String[URLs.length + 1];
                        System.arraycopy(Dum_URLs, 0, URLs, 0, Dum_URLs.length);
                        try {
                            Thread.sleep(500);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(Xelenium.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
                } catch (org.openqa.selenium.WebDriverException ex1) {
                //DefaultListModel listmodel = new DefaultListModel();
                    for (int i = 0; i < URLs.length; i++) {
                    myVector.add(URLs[i]);
                    }
                    Captured_Pages_List.setListData(myVector);
            }
        }else{
            //Please provide valid url starting with http or https;
            Date_logger = new Date();  
            log_text = Log_Textarea.getText();
            Log_Textarea.setText(log_text + "\r\n" + Date_logger + ": URL Error - Please provide the valid url, starting with http or https.");
        }  
    }//GEN-LAST:event_Capture_PagesActionPerformed
    }
    
    
    private void Remove_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove_BtnActionPerformed
        // TODO add your handling code here:
         int[] rem_urls;
        rem_urls = Captured_Pages_List.getSelectedIndices();
        for (int i = rem_urls.length; i > 0; i--) {
            myVector.remove(rem_urls[i - 1]);
        }
        Captured_Pages_List.setListData(myVector);
    }//GEN-LAST:event_Remove_BtnActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
                int atk_indices[] = Avl_Atk_Vctr.getSelectedIndices();
        Vector<String> sel_list = new Vector<String>();
        Vector<String> avl_list = new Vector<String>();
        for (int a=0;a<Sel_Atk_Vctr.getModel().getSize();a++){
            sel_list.add((String)Sel_Atk_Vctr.getModel().getElementAt(a));
        }
        for (int c=0;c<Avl_Atk_Vctr.getModel().getSize();c++){
            avl_list.add((String)Avl_Atk_Vctr.getModel().getElementAt(c));
        }
                
        for (int b=0;b<atk_indices.length;b++){
            sel_list.add((String)Avl_Atk_Vctr.getModel().getElementAt(atk_indices[b]));
            avl_list.remove((String)Avl_Atk_Vctr.getModel().getElementAt(atk_indices[b]));   
        }
        Sel_Atk_Vctr.setListData(sel_list);
        Avl_Atk_Vctr.setListData(avl_list);
    }//GEN-LAST:event_AddActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
         int atk_indices[] = Avl_Atk_Vctr.getSelectedIndices();
        Vector<String> avl_list = new Vector<String>();
        for (int a=0;a<Avl_Atk_Vctr.getModel().getSize();a++){
            avl_list.add((String)Avl_Atk_Vctr.getModel().getElementAt(a));
        }
        for (int b=0;b<atk_indices.length;b++){
            avl_list.remove((String)Avl_Atk_Vctr.getModel().getElementAt(atk_indices[b]));
        }
        Avl_Atk_Vctr.setListData(avl_list);
    }//GEN-LAST:event_DeleteActionPerformed

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        // TODO add your handling code here:
           int atk_indices[] = Sel_Atk_Vctr.getSelectedIndices();
        Vector<String> sel_list = new Vector<String>();
        Vector<String> avl_list = new Vector<String>();
        for (int a=0;a<Sel_Atk_Vctr.getModel().getSize();a++){
            sel_list.add((String)Sel_Atk_Vctr.getModel().getElementAt(a));
        }
        for (int c=0;c<Avl_Atk_Vctr.getModel().getSize();c++){
            avl_list.add((String)Avl_Atk_Vctr.getModel().getElementAt(c));
        }
        for (int b=0;b<atk_indices.length;b++){
            avl_list.add((String)Sel_Atk_Vctr.getModel().getElementAt(atk_indices[b]));
            sel_list.remove((String)Sel_Atk_Vctr.getModel().getElementAt(atk_indices[b]));   
        }
        Sel_Atk_Vctr.setListData(sel_list);
        Avl_Atk_Vctr.setListData(avl_list);
    }//GEN-LAST:event_RemoveActionPerformed

    private void IncludeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncludeActionPerformed
        // TODO add your handling code here:
         String atk_vctr = Atk_Vctr_TxtField.getText();
        if (!(atk_vctr.equalsIgnoreCase(""))){
        Vector<String> avl_list = new Vector<String>();
        for (int c=0;c<Avl_Atk_Vctr.getModel().getSize();c++){
            avl_list.add((String)Avl_Atk_Vctr.getModel().getElementAt(c));
        }
            avl_list.add((String)atk_vctr);
            Avl_Atk_Vctr.setListData(avl_list);
            Atk_Vctr_TxtField.setText("");
        }     
    }//GEN-LAST:event_IncludeActionPerformed

    private void Perform_XSSScanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Perform_XSSScanActionPerformed
         BufferedWriter bw = null;
         logincreds = "";
         
         if (Pwd_Protected_chkbox.isSelected()){
             if((!((Uname_txt_field.getText()).equalsIgnoreCase("")) & (!((Pwd_txt_field.getText()).equalsIgnoreCase(""))))){
             logincreds = Uname_txt_field.getText();
             logincreds = logincreds + "<>";
             logincreds = logincreds + Pwd_txt_field.getText();
             }else {
                 //Raise exception that the username and password are not provided
             }
         }
        try {
            // TODO add your handling code here:
            String[] urls_scan = new String[Captured_Pages_List.getModel().getSize()];
            File f = new File("source.htm");
            bw = new BufferedWriter(new FileWriter(f));
            
            //bw.write("<HTML><BODY><TABLE BORDER=1 CELLPADDING=3 CELLSPACING=1 WIDTH=100%>");
            //bw.write("<TR><TD BGCOLOR=#66699 WIDTH=27% align=\"center\"><FONT FACE=VERDANA COLOR=WHITE SIZE=2><B>XSS Scanner Results</B></FONT></TD></TR>");
            
            bw.write("<html><head><title>Results</title></head>");
            bw.write("<style>* { font-family: arial; }div.title { font-size:3em;font-weight: bold;padding-top: 24px;padding-left: 25px;}");
            bw.write("h2{padding-left: 5px;margin-bottom: 0px;padding-bottom: 0;background-color: #001f47;color:#fff;border: 1px solid black;text-align:center;}");
            bw.write("h3{padding-left: 5px;margin-top:5px;margin-bottom: 0px;font-size:1em;padding-bottom: 0;background-color: #B0C4DE;color:#000000;border: 1px solid black;text-align:left;}");
            bw.write("div.url{padding-left: 5px;margin-top:5px;margin-right:0px;margin-bottom: 5px;background-color:#778899;color:#000000;border: 1px solid black;text-align:left;}");
            bw.write("div.scan{padding-left: 5px;margin-right:5px;margin-top:5px;margin-bottom: 5px;background-color:#D6DBE0;color:#000000;border: 1px solid black;text-align:left;}");
            bw.write(".fail {background-color: #C00000;border: 1px solid black;}");   //color: #fff;
            bw.write(".pass {background-color:#00B050;border: 1px solid black;}");
            bw.write(".results div.pass, .results div.warn, .results div.fail{margin-bottom: 5px;margin-left: 40px;padding: 5px;}");
            bw.write("td.bar {width: 99%;background-color: #dddddd;border: 1px solid black;padding: 0;margin: 0;text-align: center;}");
            bw.write("h4{padding-left: 5px;margin-top:5px;margin-bottom: 0px;margin-right:5px;margin-bottom:5px;font-size:1em;padding-bottom: 0;background-color: #001f47;color:#fff;border: 1px solid black;text-align:left;}</style>");
            bw.write("<BODY>");
            bw.write("<h2>Xelenium</h2>");
            bw.write("<h3>XSS(Cross Site Scripting) Scanner Results</h3>");
            Date date = new Date();
            bw.write("<h3>Scan performed on : " + date.toString() + "</h3>");
                        
            for (int j=0;j<urls_scan.length;j++){
            //        bw.write("<HTML><BODY><TABLE BORDER=0 CELLPADDING=3 CELLSPACING=1 WIDTH=100%>");
              //              bw.write("<TABLE BORDER=0 BGCOLOR=BLACK CELLPADDING=3 CELLSPACING=1 WIDTH=100%>");
                //            bw.write("<TR COLS=2><TD BGCOLOR=#FFCC99 WIDTH=50%><FONT FACE=VERDANA COLOR=BLACK SIZE=2><B>Page URL</B></FONT></TD><TD BGCOLOR=#FFCC99 WIDTH=50%><FONT FACE=VERDANA COLOR=BLACK SIZE=2><B>"+ (String)Captured_Pages_List.getModel().getElementAt(j) + "</B></FONT></TD></TR>");
                //urls_scan[j] = (String)URLList1.getModel().getElementAt(j);
                System.setOut(new PrintStream(myOut));
                bw.write("<div class='url'> URL : " + (String)Captured_Pages_List.getModel().getElementAt(j));
                Thread Thrd[] = new Thread[Sel_Atk_Vctr.getModel().getSize()];
                
                for (int i=0;i<Sel_Atk_Vctr.getModel().getSize();i++){
                Thrd[i]= new WebScan((String)Captured_Pages_List.getModel().getElementAt(j),i+(String)Sel_Atk_Vctr.getModel().getElementAt(i), this);
                Thrd[i].start();
                }
                
                for (int t=0;t<Sel_Atk_Vctr.getModel().getSize();t++){
                    try {
                        Thrd[t].join();
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Xelenium.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
                TreeSet<String> keys = new TreeSet<String>(map.keySet());
                String txt_key = "";
                float pass_cnt = 0;
                float fail_cnt = 0;
                float warn_cnt = 0;
                String res;
                String html_update = "";
                //String trow_data1 = "<TR COLS=10>";
                //String trow_data2 = "<TR COLS=10>";
                for (String key:keys){
                	if (!(txt_key.endsWith(key.substring(3)))){
                		if(!(txt_key.equalsIgnoreCase(""))){
                			bw.write("<h4> Test Summary (No of tests executed :" + (int) (pass_cnt + fail_cnt + warn_cnt) +")</h4>");
            		        bw.write("<table style='width: 100%'><tbody><tr><td nowrap='nowrap'>Failures:</td><td class='bar'><div style='width:" + ((fail_cnt/(pass_cnt+fail_cnt+warn_cnt))*100) + "%;'class='fail'>"+ (int)fail_cnt + "</div></td></tr>");
                                bw.write("<tr><td nowrap='nowrap'>Warnings:</td><td class='bar'><div style='width:" + ((warn_cnt/(pass_cnt+fail_cnt+warn_cnt))*100) + "%;'class='warn'>"+ (int)warn_cnt +"</div></td></tr>");
                                bw.write("<tr><td nowrap='nowrap'>Passes:</td><td class='bar'><div style='width:"+ ((pass_cnt/(pass_cnt+fail_cnt+warn_cnt))*100)+ "%;'class='pass'>"+ (int) pass_cnt + "</div></td></tr></tbody></table>");
                                if (!(html_update.equalsIgnoreCase(""))){
                                    bw.write("<h4>XSS String Test Results</h4>");
                                    bw.write("<div class='results'><b>Results:</b><br />");
                                    bw.write(html_update);
                                }
                                
                                bw.write("</div>");
                                //bw.write("</div>");
            		        pass_cnt = 0;
            		        fail_cnt = 0;
            		        warn_cnt = 0;
                                html_update = "";
                		}
                		txt_key = key;
                		String key_ext = key.substring(3);
                		String[] arrkeys = key_ext.split("<>");
                		bw.write("<div class='scan'>Text Field : " + arrkeys[0] + ", Button : " + arrkeys[1]);
                	}
                	res = map.get(key);
                	
                	if (res.equalsIgnoreCase("0")){
                		pass_cnt = pass_cnt+1;
                	}else if(res.equalsIgnoreCase("1")){
                		fail_cnt = fail_cnt+1;
                                String avctr_ind = key.substring(2, 3);
                                String atk_vctr = (String) Sel_Atk_Vctr.getModel().getElementAt(Integer.parseInt(avctr_ind));
                                String escapedVctr = StringEscapeUtils.escapeHtml(atk_vctr);
                                html_update = html_update + "<div class='fail'>Field appears to be vulnerable to the below mentioned XSS String.<br />Tested value: " + escapedVctr + "</div>";
                	}else if(res.equalsIgnoreCase("-1")){
                		warn_cnt = warn_cnt+1;
                                
                                
                	}
                }
                
                bw.write("<h4> Test Summary (No of tests executed :" + (int)(pass_cnt + fail_cnt + warn_cnt) +")</h4>");
		        bw.write("<table style='width: 100%'><tbody><tr><td nowrap='nowrap'>Failures:</td><td class='bar'><div style='width:" + ((fail_cnt/(pass_cnt+fail_cnt+warn_cnt))*100) + "%;'class='fail'>"+ (int)fail_cnt + "</div></td></tr>");
		        bw.write("<tr><td nowrap='nowrap'>Warnings:</td><td class='bar'><div style='width:" + ((warn_cnt/(pass_cnt+fail_cnt+warn_cnt))*100) + "%;'class='warn'>"+ (int) warn_cnt +"</div></td></tr>");
		        bw.write("<tr><td nowrap='nowrap'>Passes:</td><td class='bar'><div style='width:"+ ((pass_cnt/(pass_cnt+fail_cnt+warn_cnt))*100)+ "%;'class='pass'>"+ (int) pass_cnt + "</div></td></tr></tbody></table>");
                        if (!(html_update.equalsIgnoreCase(""))){
                            bw.write("<h4>XSS String Test Results</h4>");
                            bw.write("<div class='results'><b>Results:</b><br />");
                            bw.write(html_update);
                        }
                        bw.write("</div>");
                        bw.write("</div>");
                        this.map = new HashMap<String,String>(); 
                      //  bw.write("</div>");
                        myOut = new ByteArrayOutputStream();
                        this.stdOput = "";
                        }
                       
            bw.write("</body>");
            bw.write("</html>");
            bw.close();
            Desktop.getDesktop().browse(f.toURI());
        } catch (IOException ex) {
            Logger.getLogger(Xelenium.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                bw.close();
            } catch (IOException ex) {
                Logger.getLogger(Xelenium.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_Perform_XSSScanActionPerformed

    private void Pwd_txt_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pwd_txt_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pwd_txt_fieldActionPerformed

    private void Pwd_Protected_chkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pwd_Protected_chkboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pwd_Protected_chkboxActionPerformed

    private void Pwd_Protected_chkboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Pwd_Protected_chkboxItemStateChanged
        // TODO add your handling code here:
        
        Uname_txt_field.setText("");
        Pwd_txt_field.setText("");
        Uname_txt_field.setEnabled(!(Uname_txt_field.isEnabled()));
        Pwd_txt_field.setEnabled(!(Pwd_txt_field.isEnabled()));
    }//GEN-LAST:event_Pwd_Protected_chkboxItemStateChanged

    private void Pwd_Protected_chkboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pwd_Protected_chkboxMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_Pwd_Protected_chkboxMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Xelenium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Xelenium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Xelenium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Xelenium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Xelenium().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JTextField Atk_Vctr_TxtField;
    private javax.swing.JList Avl_Atk_Vctr;
    private javax.swing.JButton Capture_Pages;
    private javax.swing.JList Captured_Pages_List;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Include;
    private javax.swing.JTabbedPane Log_Tab;
    private javax.swing.JTextArea Log_Textarea;
    private javax.swing.JButton Perform_XSSScan;
    private javax.swing.JCheckBox Pwd_Protected_chkbox;
    private javax.swing.JTextField Pwd_txt_field;
    private javax.swing.JButton Remove;
    private javax.swing.JButton Remove_Btn;
    private javax.swing.JList Sel_Atk_Vctr;
    private javax.swing.JTextField URL_Txt_Field;
    private javax.swing.JTextField Uname_txt_field;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
